# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: user1234
  CLOUD_SQL_PASSWORD: avhk0501
  CLOUD_SQL_DATABASE_NAME: todo-app-mysql
  CLOUD_SQL_CONNECTION_NAME: to-do-app-346414:us-central1:todo-app-mysql
# [END gae_python37_cloudsql_config]
